  steps:
    - id: 'Install Dependencies and Build React App'
      name: 'gcr.io/cloud-builders/npm'
      args: ['install']
      #dir: '.' # Assuming your React app is in the root directory
    - id: 'Build React App'
      name: 'gcr.io/cloud-builders/npm'
      env:
        - 'VITE_API_BASE_URL=https://notebook-service-91248372939.us-central1.run.app/api'
      args: ['run', 'build']
      dir: '.' # Assuming your React app is in the root directory
    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['-m', 'rsync', '-r', 'dist', 'gs://arctic-sentry-467317-s7-studenthub-frontend']
    
#      args: ['rsync', '-r', 'build/*', 'gs://arctic-sentry-467317-s7-vertex-ai/']
      #arctic-sentry-467317-s7-studenthub-frontend']
  options: 
    logging: CLOUD_LOGGING_ONLY # This is commented out.
    defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET    
      #env:
      #  - 'NODE_ENV=production' # Ensure a production build
#  artifacts:
    #- repository: 'https://LOCATION-npm.pkg.dev/PROJECT-ID/REPOSITORY_NAME'
 #   - repository: 'https://us-central1-docker.pkg.dev/arctic-sentry-467317-s7/student-hub-repo'
  #    packagePath: '.'
    # 1. Build Docker Image for Studhub Frontend
    #- name: 'gcr.io/cloud-builders/docker'
    #  args: ['build', '-t', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/student-hub-repo/studenthub-service:${SHORT_SHA}-${BUILD_ID}', '.']
    #- name: 'gcr.io/cloud-builders/docker'
    #  args: ['push', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/student-hub-repo/studenthub-service:${SHORT_SHA}-${BUILD_ID}']
      # Optional: If you want to deploy to Google Cloud Storage
  options: 
    logging: CLOUD_LOGGING_ONLY # This is commented out.
    defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
