#/**steps:
  # 1. Build and push Studhub Frontend
#  - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/student-hub-repo/studenthub-service:${SHORT_SHA}-${BUILD_ID}', '.']
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/student-hub-repo/studenthub-service:${SHORT_SHA}-${BUILD_ID}']
#options:
  # logging: CLOUD_LOGGING_ONLY # This is commented out.
#  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

#images:
#  - 'us-central1-docker.pkg.dev/$PROJECT_ID/student-hub-repo/studenthub-service:${SHORT_SHA}-${BUILD_ID}'


  steps:
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
      dir: '.' # Assuming your React app is in the root directory

    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
      dir: '.' # Assuming your React app is in the root directory
      env:
        - 'NODE_ENV=production' # Ensure a production build

    # Optional: If you want to deploy to Google Cloud Storage
    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['rsync', '-r', 'build', 'gs://arctic-sentry-467317-s7-studenthub-frontend']
      dir: '.'
