  steps:
    - id: 'Install Dependencies and Build React App'
      name: 'gcr.io/cloud-builders/npm'
      args: ['install']
      #dir: '.' # Assuming your React app is in the root directory
    - id: 'Build React App'
      name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
      #dir: '.' # Assuming your React app is in the root directory
      #env:
      #  - 'NODE_ENV=production' # Ensure a production build

    # 1. Build and push Studhub Frontend
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/student-hub-repo/studenthub-service:${SHORT_SHA}-${BUILD_ID}', './']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/student-hub-repo/studenthub-service:${SHORT_SHA}-${BUILD_ID}']
      # Optional: If you want to deploy to Google Cloud Storage

  options: # logging: CLOUD_LOGGING_ONLY # This is commented out.
    defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
